name: attribute_localizations
description: Attribute localizations.
version: 1.0.0
author: hsul4n
homepage: https://github.com/hsul4n/flutter-localizations/packages/attribute_localizations

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
