name: attribute_localizations
description: Attribute localizations.
version: 1.0.1
author: Bassamhakimi
homepage: https://github.com/Bassamhakimi/flutter-localizations/packages/attribute_localizations

environment:
 sdk: ">=3.0.0 <4.0.0"  # Dart 3 compatible
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
