name: validation_localizations
description: Validation localizations.
version: 1.0.0
author: moaidalrazhy
homepage: https://github.com/MoaidAlrazhy/flutter-localizations

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.18.0
  attribute_localizations:
    git:
      url: https://github.com/MoaidAlrazhy/flutter-localizations.git
      path: packages/attribute_localizations
      ref: 1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
