name: validation_localizations
description: Validation localizations.
version: 1.0.1
author: Bassamhakimi
homepage: https://github.com/Bassamhakimi/flutter-localizations

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"  # Updated for Dart 3
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.20.2 
  attribute_localizations:
    git:
      url: https://github.com/Bassamhakimi/flutter-localizations.git
      path: packages/attribute_localizations
      ref: updated-intl

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
